# Generated by Django 4.0.3 on 2022-03-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('westernunion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
