# Generated by Django 4.0.3 on 2022-03-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westernunion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default=123, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('holder', 'name'), name='uniq_acc'),
        ),
    ]
