# Generated by Django 4.0.3 on 2022-03-09 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('westernunion', '0002_bankaccount_name_bankaccount_uniq_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Сумма'),
        ),
    ]
