# Generated by Django 4.0.3 on 2022-03-10 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westernunion', '0002_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_acc', models.ForeignKey(default='Счет отсутствует', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sending', to='westernunion.bankaccount')),
                ('to_acc', models.ForeignKey(default='Счет отсутствует', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='receiping', to='westernunion.bankaccount')),
            ],
        ),
    ]
